<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ContentGenerationController extends Controller
{
    public function __construct(protected \App\Services\OllamaService $ollama) 
    {}


    public function generate(Request $request)
    {
        $request->validate([
            'article_id' => 'required_without:note_id', 
            'note_id' => 'required_without:article_id',
            'prompt_id' => 'required|exists:prompts,id',
            'custom_instructions' => 'nullable|string'
        ]);

        // 1. Get Prompt
        $promptTemplate = \App\Models\Prompt::find($request->prompt_id);
        if (!$promptTemplate) {
            return response()->json(['error' => 'Prompt not found'], 404);
        }

        $context = "";

        // 2a. Handle Articles
        if ($request->filled('article_id')) {
            $articleIds = is_array($request->article_id) ? $request->article_id : [$request->article_id];
            $articles = \App\Models\Article::whereIn('id', $articleIds)->get();
            foreach ($articles as $article) {
                $text = strip_tags($article->content ?? $article->summary);
                $context .= "Source Article: {$article->title}\nContent: " . substr($text, 0, 10000) . "\n\n";
            }
        }

        // 2b. Handle Notes
        if ($request->filled('note_id')) {
            $noteIds = is_array($request->note_id) ? $request->note_id : [$request->note_id];
            $notes = \App\Models\Note::whereIn('id', $noteIds)->with('article')->get();
            foreach ($notes as $note) {
                $context .= "Source Note (from {$note->article->title}):\nQuote: \"{$note->quote}\"\nUser Annotation: {$note->annotation}\n\n";
            }
        }
        
        // 3. Prepare Final Prompt
        $finalPrompt = str_replace('{{content}}', $context, $promptTemplate->content);
        
        if ($request->filled('custom_instructions')) {
            $finalPrompt .= "\n\nAdditional Instructions:\n" . $request->custom_instructions;
        }

        // 4. Resolve AI Config
        $aiConfig = null;
        if ($request->filled('ai_config_id')) {
            if ($request->ai_config_id === 'round-robin') {
                // Pick random FREE, ACTIVE provider
                $aiConfig = \App\Models\AiConfig::where('mode', 'free')
                    ->where('is_active', true)
                    ->inRandomOrder()
                    ->first();
                
                if (!$aiConfig) {
                    // Fallback to any active if no free ones? Or just fail/default?
                    // Let's log warning and use default system setting (null)
                    \Log::warning("Round Robin requested but no active 'free' providers found. Using default.");
                }
            } elseif (is_numeric($request->ai_config_id)) {
                $aiConfig = \App\Models\AiConfig::where('id', $request->ai_config_id)
                    ->where('is_active', true)
                    ->first();
            }
        }
        // If $aiConfig is null, OllamaService uses system defaults (Settings table).

        // 5. Send to AI
        try {
            $response = $this->ollama->generateText($finalPrompt, $aiConfig);
            
            $providerName = $aiConfig ? $aiConfig->name : 'System Default';
            $providerModel = $aiConfig ? $aiConfig->model_id : 'Default Model';
            
            // Append Watermark
            $response .= "\n\n_Generated by {$providerName} ({$providerModel})_";

            return response()->json([
                'success' => true,
                'content' => $response,
                'used_provider' => $providerName
            ]);

        } catch (\Exception $e) {
            \Log::error("Generation Failed: " . $e->getMessage());
            return response()->json(['error' => 'AI Generation failed: ' . $e->getMessage()], 500);
        }
    }
}
