<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ContentGenerationController extends Controller
{
    public function __construct(protected \App\Services\OllamaService $ollama) 
    {}


    public function generate(Request $request)
    {
        $request->validate([
            'article_id' => 'required_without:note_id', 
            'note_id' => 'required_without:article_id',
            'prompt_id' => 'required|exists:prompts,id',
            'custom_instructions' => 'nullable|string'
        ]);

        // 1. Get Prompt
        $promptTemplate = \App\Models\Prompt::find($request->prompt_id);
        if (!$promptTemplate) {
            return response()->json(['error' => 'Prompt not found'], 404);
        }

        $context = "";

        // 2a. Handle Articles
        if ($request->filled('article_id')) {
            $articleIds = is_array($request->article_id) ? $request->article_id : [$request->article_id];
            $articles = \App\Models\Article::whereIn('id', $articleIds)->get();
            foreach ($articles as $article) {
                $text = strip_tags($article->content ?? $article->summary);
                $context .= "Source Article: {$article->title}\nContent: " . substr($text, 0, 10000) . "\n\n";
            }
        }

        // 2b. Handle Notes
        if ($request->filled('note_id')) {
            $noteIds = is_array($request->note_id) ? $request->note_id : [$request->note_id];
            $notes = \App\Models\Note::whereIn('id', $noteIds)->with('article')->get();
            foreach ($notes as $note) {
                $context .= "Source Note (from {$note->article->title}):\nQuote: \"{$note->quote}\"\nUser Annotation: {$note->annotation}\n\n";
            }
        }
        
        // 3. Prepare Final Prompt
        $finalPrompt = str_replace('{{content}}', $context, $promptTemplate->content);
        
        if ($request->filled('custom_instructions')) {
            $finalPrompt .= "\n\nAdditional Instructions:\n" . $request->custom_instructions;
        }

        // 4. Resolve AI Configs (List of candidates)
        $configsToTry = collect([]); 
        $isRoundRobin = false;

        if ($request->filled('ai_config_id')) {
            if ($request->ai_config_id === 'round-robin') {
                $isRoundRobin = true;
                $configsToTry = \App\Models\AiConfig::where('is_active', true)
                    ->inRandomOrder()
                    ->get();

                if ($configsToTry->isEmpty()) {
                    \Log::warning("Round Robin requested but no active providers found to cycle through.");
                }
            } elseif (is_numeric($request->ai_config_id)) {
                $config = \App\Models\AiConfig::where('id', $request->ai_config_id)
                    ->where('is_active', true)
                    ->first();
                 if ($config) $configsToTry->push($config);
            }
        }

        // Always add "System Default" (null) as a fallback if the list acts as "try these, then default"
        // But for Round Robin, we stick to the list. If list empty, we fallback to default ONCE.
        if ($configsToTry->isEmpty() && !$isRoundRobin) {
             $configsToTry->push(null); 
        }

        $lastError = null;
        $success = false;
        $responseContent = '';
        $usedProviderName = '';
        $finalModel = '';

        foreach ($configsToTry as $config) {
             try {
                 $providerName = $config ? $config->name : 'System Default';
                 \Log::info("Attempting generation with provider: {$providerName}");

                 $responseContent = $this->ollama->generateText($finalPrompt, $config);
                 
                 if (!empty($responseContent)) {
                     $success = true;
                     $usedProviderName = $providerName;
                     $finalModel = $config ? $config->model_id : 'Default Model';
                     break; 
                 }
             } catch (\Exception $e) {
                 $lastError = $e->getMessage();
                 \Log::warning("Generation attempt failed with " . ($config->name ?? 'Default') . ": " . $e->getMessage());
                 // Continue loop if Round Robin, else break
                 if (!$isRoundRobin) break;
             }
        }

        if ($success) {
            // Append Watermark
            $responseContent .= "\n\n_Generated by {$usedProviderName} ({$finalModel})_";

            return response()->json([
                'success' => true,
                'content' => $responseContent,
                'used_provider' => $usedProviderName
            ]);
        }
        
        return response()->json([
            'error' => 'AI Generation failed after attempts. Last Error: ' . ($lastError ?: 'Unknown error')
        ], 500);
    }
}
